; generated by PrusaSlicer 2.5.0+win64 on 2023-05-10 at 19:24:09 UTC


;
; thumbnail begin 16x16 612
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABkUlEQVR4AY2Ty0oDQRBF+6dUxLzfmU
; cmM84jBh8QiBgQ/QBBRFfu/AK3bly4cqErv6z0FNQQBo1ZXKan+95b1dVVrlarSb1el0ajIc1mU1qt
; lqLT6chwOCxh+3DgokHrTNhut1XU7Xal1+vJYDCQyWQivu/LeDzWPc7gwDUjZwd8+/2+RguCQKbTqX
; iep8AkDEMZjUbKgWtGDrERQZqmEsexRo+iSMEaA/YxJwhGaB2p4kzEoijkLA3l8aQnr8uafK325ONi
; X9fsLVNfeZiiQetYJEmika9mvor+AmY386EaYERtHGmxUSTRRvG6yWXu6ZWAo0DckRS3MQBPp53yhU
; qD++PB1gYP8zUDFmAeB5ref+LP8x0tNBqu7ygEBeFnlY3lfblZfH0UlEXXIvIULHDkYPZTzLtZW14W
; B/K22FU8L5pym9XlMPQkz3PlodFnpBmsF7iTvUoVZJllmTYSYpqOZnI2A9b/GEEiI+tOxPzTgXCslf
; nqMDFl1WGymbCuqw4TGh2m38YZgmVjEU1UHedv8a/8SKemNGwAAAAASUVORK5CYII=
; thumbnail end
;

;
; thumbnail begin 220x124 10100
; iVBORw0KGgoAAAANSUhEUgAAANwAAAB8CAYAAAACRt5vAAAdXUlEQVR4Ae2daX8WRdaH7y8yy+Mgbr
; jgCiokbCGBhLAlkLAFCAkIQRCVQFAWQSICgoCAGmR1RQadGX/6+Dwvxg/iV6m5r5qpTKfTS1V1Vd/d
; oV+cXyC5l+6uuvqc8z+nqmtz5swRaTZ37txEa2pqmmDt7e1ixYoVorW1Vf6/ubk51ubNmxdp8+fPj7
; QFCxbE2sKFCyNt0aJFsdbS0pJoixcvTjXOM87WrVsnbdmyZZP+1tbW1hALH8fSpUvFmjVrxPr16+W/
; 485F51qkXc+ksYgbv6Qxj5sncfMqaS4qW7lypfxePic4r9M40GGp5ho2ZZxcT0+POHjwoBzkMoGWBT
; BlGzZsEJ988olYsmRJw8AyNWDbtm2bGB4e1jrHLPAVDTxe++abb4rXX39d/j1uXmeFruYDNuXVOPA9
; e/aII0eOyAuZBJoNbKag+YZMTdze3l7xzTffiE2bNmlNdKDMw3SOpaOjQ3zwwQfi2LFjsR4xL/hMwT
; OFLgjewMCAGBkZkefC/5PmdhboajawpYEW5c26u7vlxY26AI0CzRVgygil165dK4FrFFSuYOR33DCi
; /pYVwCKBx/EQifH3qLlrC54RcC5hC0JHmHXq1CmxatWqUoKWFIrt3r1bfPvttzJ3tZ30fI4PywIiId
; bZs2fl57Rp5oRlAI9jO3HihEx5eG3S3HUJXc1lCKkjinDX3LFjh7zgURelEaDZQBb0al1dXeL06dMy
; 2W4EUD6B5PxIC/bu3ZsIXRb4fIIXBRyfvXr1ahlG8j4dUcVViFnLEzZlXAhOGOWOQTX1aiag+YBMwa
; PCR0IS13Ax0bOYawj53ZYtWybcVPKCzwS8JG/Hexgr5h6fa6pkuoCulgU2U7k/fKfB2126dEn09fU1
; HLQ0wIKGsHD06FFx7949mZuaApYVJldmCiA/33rrLXHz5k05adPyQB348gKPUP/ixYtSgeU9abmdTY
; ipA13NNWwmCiQXgjsmuR0XPylcyBu0uBALr4xXI7dJm7SuwABwHcsDRP7OeG3fvn08QtERYXyDlxRm
; AhvXB+8WF2a68nZpPNUaCVvQOjs7xebNm+VFsQEtDjZXoDFgO3fuFIODg1L0yQqYLkS+LCuA/J4IZd
; euXd7BM8nxgnOH46K2xrEqzSApt8sDuppP2ExUSC4QHRkUixFVsno1E9DShA4m6EcffSRu3Lghli9f
; bgxYo+FyDWEQvKGhIfH9999L+NIEGB/gxUHHDZy5xA2B32UtH7iCrpYnbDqiiAIAT+cKNFNvFpxQhC
; NMJnIWHchMJzl34TzNB4SotHj9jRs3aqmfJl7PBjxuiqQqfKatkukLulqRYAt6NS7svn37ZK4Qvsi+
; PFoYtNHRUSmJJ028ooLlC8Qk8PgcOlS4WdqCl8XjkVtTnuE4TJXMvKCrFQW2qNCAu9SZM2ekh3Hh1d
; IgC4aKfC+DZwOZzYQnBPJpPiCMujYoznfu3JHN0DrlBhPwkqDjHE+ePCm/X0dUaRR0taLCFrxzMSjk
; d/z0CRqTCMgpiPqAzDdUPmE0gY//E9bhcXTrfLbg8RqlHJsqmY2ArpYnbLZyv7qwtIVRR2FQXYKGcU
; dGFKHVRwc0X4AxUV1a3gAGrx2fdeXKFZkWuAaPOYEgcvnyZTl2USGmbc3OJ3S1IsGWJowwQADBBQ5C
; lzV8ZAK98cYbsn0pzZu5AMw1VL5htPV8XEsaA86dOyeFlbgSgyl0/B0RixyfzzVVMhsJXa2osCXlag
; gaqGKAFx4cE9BU0V2FkD4gywoF52piviG09XqEfIwXn5EFPD6HsQc4E0GlKNDV8oZNN4RME0YYIEQN
; 1m4xUUxAwyiy//DDD3KtnilorgAzhcmVuQLQFDwguX37trzmSUX1OFXzwIEDsraGCmqjYtrkda6h0w
; KukbClCSNbt26VYQt3vSTYgrkFWwmgZqF+5gVZGgSbVi8Tb65tEyO9i8UHGxaKy33zxJ2tc6T9beBl
; af87ODvS+Nvd/lelXdvcJN97buN8cWxdixhas0QMdLWLtSs7M0PoAj6+i+4Prr3ydlHghbt8aBRn3H
; iPiZLZaOgSgSs6bHG5GoNAeEjXAwMaBxvhCKt6ATQraLaAMfEBC6gUTP/c8VIuxncBJDAqEG0BzAoe
; uRcQIagkeTt6Vtn2gc82EVSKCl3NNJQsCmxRvY6HDx8W58+fH+91DHq1/v5+8csvv0godWCzAS0OMD
; wNEx1vlBdcusYxcWzcAOIAdAVe+LrzOlaLsMA1qHAq2Lg5Ug9VKzKScruiQJcWWtamAmzBOyJ5AjU7
; JoMaQO6QDJrqGjcFzRQy5cHy9F6ujLAUDxgXhprClwYer8HTEWKqMeM1/J/vCwI4FaCrZQklfaiRWW
; ALejX6+kiwx8bGrD2aCWSEaEzUInqxLN6PfNDU89mApyD7/PPP5Zo75fHSBBXX0NmolyahZc0VbDre
; LS/YGCxUyB9//FHWgMjv4mDLChrhYhk9malxjnhtxB2X4AXHZf/+/fIGyZjFrU5oBHRRc90WOi3gXI
; SSWWAzkfsZVNQswko1mMBHqMkkSIJNFzTu+Nz5ywSMM6+3fbYUe6K8ni54YegQUNi+gb8FvR03SpPy
; QZ7Q2YaWtbLDFgSNOs39+/flIIfDFfI4QkyleOnAVoGWbCbgRV1zcrcLFy6IQ4cOjcMWNBRKxkzlcq
; berojQ1VznbY2CjY4R1K6gMBK+k1KzIz/gjqomQQVaY8BDSabDB9U47PWCgsprr70mjh8/Ln9fBujS
; QsuaiXcrGmwMCuEjLUPBEDItV0NQIWRRamYcbKh0FWhm4IVzvPD15WZHiYYwn7+n5XbKuFmqHtqyQR
; cJnO9QMotAEgUbg8S2B2wpzt1SFzbl1Si4Xrt2TTYsR3m1Y+tbSjXZi2LkeFy7cEmBawxkXHMa0IOw
; 6ULH6oCvvvpK3ijToMsipPgMLWuNCCWzwsZg0ZrFbsdpkn9SrkZPHvun4PGAVoaP3e2yFlWmSV5Eu7
; N1rryWCjiuMR4K6EwElfD4EtEwZuEaXVbo8gota40OJU1gY0Dow0P4CEr9NrAFvRqDyN1zdPPSUk3q
; ohvebnRLuzgyMjy+AWtUmGkKneqHRdmM2kFNF7pGhJY1197NFWxh4BiIq1evis8++yxyEEzl/gm52q
; rl4tbgwlJN5jLZ/d1toq9rmbGSmQYdogvPc+CnbZ3OBDoXXq7m07u5EknwZoQi3M2i1q1lgY2w50Eo
; XDfauMZv9rQ5h445gZFi+BBRXHu5TMC5ytviYONCfvzxx3IDVnWBs8A2uR2rCiHzNEJMlh+llQ9MoQ
; vuGBbcqs8WOpPQMhNweXk3nbyNiwlsXMS4/UWywDbS21qqyTqVDBXTB3Qsv7p+/brM7Vzmcy69XK1o
; 3o0LiGcjhEzazCdJIEmDjZ7AMk3QqWiMgQl0OkKKmidq64wierlaI4WS8MWgvkJdjQ19krapywJbVV
; 8rjp3btMAZdFHzhbYx6qy60OUhoNRcezebUFLV1+ip42EZ4cWjttL/pHVq9aS9TBPyQbC08NKkZBBe
; YYCnY88bejZ9h5ZGwPnybjqhJBcFz0brTrhH0mXeVgkkxbU09dImnwsWxVl8DHS812VoaePlao30bt
; RPfvrpp/HH2YZhcxVKUgMq0wR80Az1khuij9AyOK/YNJbnRTTSy9V8KZNJ3o0LQOcBalJ4D3ofedvd
; bVWrVtGNOh0NCK6hC84tXsfqAwQVPsPGy2VVLDMBpxtOBk+Mk0UUoWs8XODW9W4medu1LU2lmngPsq
; WJKLqhZZyXU6olr+FGTy+ujpdzGVYmAue67sbd5eeff5aSf9L6Nlfercrbymcm+ZyNl1PQ8ZNnVfDc
; b17jqy6XCJxP70bDsboQUe1bNkJJWn9k1bJVPssSWuoIKMHanOpmQrTj/Xl4OW3gbLwbJ0VbFvWQqC
; KkS+9WFbenjpmEljZeLqouR5fKe++9J//vUzypuQ4ng3cIGkpv3bo1/vhXHdh0c7ck79ZTv0OWaYJV
; NtFQLQe7OzJ7ubRcLggcv2PpF4uag57OdVhZ8xFOchKsV+LC6Kx1c+3dqm0Rym+MYV5eLjxH1dz1EV
; bWXIaTnBTbjX/55ZfGq7gr71ZZ0PByaWvoTL2cyUJVVh2w/pLvdRlWOgOOE6Kaz3OWlUvO4t1sgaty
; t6lj4QZnX+JJVOcJP6kTs2OYd+BMwkmVcJKnBR+Sp+vhXNbdOIZKmZw6xlj2JCiWNnU5XQ8X1CJQMa
; kb83vbsHICcLb5m2qXYSemoLqj691ch5O711Z1t6lmb/UsaUhYGS4PUDtmOwcaN7LkcdbAcVLs7Uh3
; v8kyHJfqZDipRk4u02SqLN1sSwS2amVS1wkRnNp9wBtw4TiVA2b3YjqwOWCTlQE+1ckqnJyaRh8sY5
; u3WpnUW0mxXG2taJrHGQHHAfI4IVpidHsnXeZvlTr5YFpfV6e3sFI3jwsLJ+R1qPG0K3oBjoPmSzhI
; k2blrN0lusAR65dpElWmbz7zuCUWq8HV/FdzmLzOGrhwHMoJ0eCJC7VZHeBLMKlauR4cc53H2QonUa
; UB9TtWwCCspCmVicDxpeycxWODbJfj5CGYEONXgsnUNZZY2eRxPoSTuI4TjuPKlSuySd8YOD6Ug2eR
; aNb1b74K3mHg2Mu+TJOoMn2zFU5cFMBNVw7wPriJBS4cZ1LEZucsHimUVIPT3U4hL4WyWtU9dQ31ud
; FKpcnKAQxhcXh4eFIeVwt6Nj6YRwkFCW0kcFWHSWUYfZW6wLlUKm2AC6ZjR44ckbXqoKer0bJCPQHI
; 6IXU7TKpgKusAi69+M3ncOx8D88krB09elT8/vvvci2QSVtXBVxlFXB63SYcx2+//Sbu3r0raiwSpW
; WFGhs/ywrcX/tnl2oSVaZvf+9/qbTAwRTHwfdQWhvP4ZTCwtMlObmyAXerr/JwU9X+uvmF0gHH5544
; cUJ+TqRoElQpqSew6rVMKuWnm6qywFS1Gxtnl0alVLDdvHlTaiKTVMqoOhxfwEEl1eF8AWdbh/uwpw
; JuqtqZnlcKVYdLAg4Rks807jRRISY7GbHyteidJm93VZ0mU9WGVzcXvtME5zQ2NjYBNuPWLoyT+/DD
; D2WIWeReyv7li0o1iSrTt4GOuYXtpVTGU3r47Ey9lMEcjhNAyQwuMy/SaoGuFZ3ift+zpZpIlaXbrw
; MviK5Ouwd9+F4twGcRQuJ9k8oCmdbDnT17Vhw4cEAbuLzWw0nhpOe5Uk2mytLtwsonE8PJRq2Ho6H/
; 66+/lt/pbQGqWvFNkZwvCh5IEVZ8v7WyenDHVLPXWp8v1Ipv/s3nDQ0NRfZRZgYurjTAlyJ78hSSIi
; iVWO/ytiqsnEJGONmzZH7m/M2VQklfJGUzPl+3y8QZcGrF6+nTp6WFDzIP4STKy33SXQE3Vezs8hle
; w0kT4FDrP/30U/kek7auSOCy7EvJgaqnj2C+87i0sHJo2avi/wdfLNXEqmyy4d3WL36lIR0mYeDwbH
; x+XElAVzBxuvMyJ4BiwxqgRoaVqJVja58p1eSqbLJdXPH4JHUy73CSucyz53XXwaV5Ny/PFhgZGZFP
; IGlkWFl5uXIb3m1n6wsNDScPHTokeyFNFp46Ay4trAwekIKLMJMTdlWPM/VyV7ufLtUkq+y/NtrxhL
; V3c1F/o6tft8PEJH/z/nw4FB0EFS6KzzavKC+3o/0V8UOlWJbOftr6vNiwaJZz75YWTvKTDbMoeel0
; mCR5t7j8LZcnoLJR5rFjxxI9nGvxRHm5453PVKFlyWz/wumTYHMtlkR5OHYT37Vrl/U+JjreLbdnfH
; NC7NkXPlGX4kmUl+tbtlB83jWjVBPuQbaPlj0m624uvJtuOMl3oULaNCybhpOTgPMRVgbFE7zdF198
; IUNNWy9nCt2upbPE9xtnlmriPYj23YaZYsu8p6xhM/VufM/t27elZ0vrLnEVTqYC5yKsDKuVbAu9b9
; 8+WUJw4eV0QssDS2eKf2yp+iyLaqiSu5rchZJp3o1tD1hyRqdU1vVvJuGkMXC2YWUYOk6cljDgY8cw
; n14OW7u8XXzQ8XiVzxUUtuF63tbd0ZoImwvvxuv27NkjgdPtnXQZTkrg5s2bJ/L2ciqvo6jIUnS2h8
; 6iWOqElvRZVtAVzw4vmibWti8yCiVtlEkWiN67d08MDAwYrQxw6d1gzRg4V14umLSyuBXzGVryPQPt
; c8WlVU9V0BXEjrdOF+va5noPJdEMSGH4u8nKANfebRy4NOhsxRPddXJcFC4yrTQoRrpezjS0VNBdXF
; 55uiLA1qsBm20oiZGjUQfmdTbr3lyKJYozLeB8ezlldKdcvXpVbtXnE7ptdehOd86ooGuQvVsPI6Ma
; k13DduvWLfkzqaskT++WCFzeXk55Oi4k7p/2GhehZRJ0o/Wc7pf+F0o1WctsCCQH5v/FyrOZhJKEkL
; zfdFWAL+8WCZxPL2cKnQKP5lFKCL6g29DZIg63PiruVnU678bC4N2v/lmsiRBIXMHG3v03btxwDpsr
; 75YKXBbFMktoqS4W8u37778/Ia9zDR3q5aHWJ8StnqerENOTfbp6htj26jQp/fuCjc9hdzleo9OgbB
; tKmiqTicBl9XImoaUudEpQATp+muRzOtCp4vhQ2wviTMdj4ucqxHRmhJDvLZ4utjQ9EQmaKWxReZts
; 4fvP8zF0VwMkwZYllEzzbpHAFS20VMZgsGPYyZMnE72cDnRR4NG4em7kdXG47bG6t3uqVBO7iPbFmi
; fF4Kw/iPf3Dshd3mhwSALNBjae/IQwEgwhixpKjgPX3NwsfHo5k9BSBzoeXo7yFB4AW+hUHZAOBArx
; vZ1t4vXWZ8Xp9kfF36t2MGMjV3tv8cNi65xH5Jo2Cs6MGREKYpgL2Pg748bnmiwsdRlK2gAHa5HAFT
; W0VEVxBo1eOJJkE+jC4DEJ6DxA1QqGPPx7c3uzONTyiBjrflL8X5XbadmFen1zoO7Velsnq5Dc1Bgz
; Sj5JoKXBxvvVo9V0lt0UJZScAJyOl/MZWtpAx2CxvfTly5flgJp6O+6O165dE4ODg7G53ep6bre9bZ
; YYWfSIuLH2qQq8GLu6aoYEbcOC5xNzNUBhvHgUL68zAQ27ePGiuHTp0nhI6Qu2rKFknHdLBM53aOkC
; OgaFBmhCFUIXHegYeGp83HFpoE4TVJgYPfUwc3vbS+Lgoun/Bm+gAk+BtmfOn8WmpqfE6nr4qCOMKA
; EMb0depxtCIowo0SxP2Fx6twnAFQG6pHwuaf0cA9nd3S0OHz4sBycOOranZgk9gJoIKgq8dctaxGDr
; S+JAHbzPumaIv21+8HK8f2x9XnxcDx37X/qDEWjhEJL37Ny5U+zfv1/+Ow42ykKE/Sart12JJK5hmw
; Scj9AyL+gYRBYTsllnlKcDtgsXLkiPqCOoJIG3Znm7GKiDx7KS0SWPiG/WPzPlvd7tep3yZP1cAW19
; PXQ0BS0qX8PDjY6OinfeeScSNv727rvvlga2pFBSGzgdL5encpkEnarRES4ymAo4whGVM+gKKjrgke
; NtWtosdi94XBxc8JD4ZOUT0utNFfiADLV2x+w/ir5Xpoveln/3P2YFLRxC8n8VYiroGLOkTYBMYXOt
; SNp4t0jgXIWWLpVLHejC4JEn3L9/XworKswMh5guwBsPNztaxNa22ePwnel4VNzufbp08AEZxw5kW2
; b9Sayf/7zoiukQyQpa2KsdPHhQ/PrrrzJSSQItK2ymiqSLUDIRuCKKKKbejkWtbHt26tSp1JqdK/Ci
; 4Bte+HA97KznfKtniHubZhYOwDv1mwLLlQ4t+IvYVg8X++Y+LkPG7qULEyFzCZoaE3JwbpB79+6V77
; HxakUTSSYB19TUJHShyyOfy+rtEEQIR9SAMZiEK0yE4CDrQpcEng58hJ0b2heIba0vSgDfmDdNHKsX
; hgnV6DG8t3Gm+DGHMJT9Hr+sw3VpxeNyLdq+pv8R2+terP+VaWLT/Jmip147W7W80xqyONB0YCOUpO
; lA3SyV+kyDA+935dUalbcpgzUJXBx0Ol7OBXQuQkwmCosNuUOqBtZgWILSxS5NDKyNt8sCXhjA3roH
; 3LxkjhhseU4M1SHc2zxNDM9/SLyzcJo4WofxwzqMl1Y8Ia7Vi+4YrWbsPBa2u/+xr9Y9I+1mvWRxuZ
; 5HYgB9tOVh8XbzQ2Lny38Sr738RzE4Z5rcGYuNVtW2BmmA+QSNutx3330nn7UWDiH5SUsYtTe1y5ur
; ENInbHHAKc7GgSszdEwIygL0QzKQcXkdA0x3SrhmFweeLXy6ACoIse668gmIG+siTF8dxv7FL4qBRc
; +JHQueFDvnPyZtqHm62BWwnVjTdLGj+TExOG+G2LbgabFt/tNi68JnxaaWWWJ9W5MEq6uz3QiuNMBM
; IYsqYiNs0TVCLTQpX+MGyXipjX/KDJsWcD6Vy6x5HQNEpwhhJJNAR1BhsAlVCDvzAM8EPh0w48zFd+
; icS1bQCB/pW+WYdYURtS8JqQHguczXfCqSqcCVBTqMAbty5Yqs03QENofRVTIB7vr163Lww5PCBjwT
; AF1B6BuuJMBMQVNSPztnBSV/HQVSeTXGii048I5Rc6LosEUCV1ToguBxlwO48EaepuUDqSjWw0zunl
; GLW/OCzweQWb7bJWSq7xERhLA/uGjURu5Xx0B0kkUcaQRsscDlAZ2NgslEovFVxfO6gopOmEnth/DU
; Bjwd+FxA6MN0jzvp3JNAo28VMcsUtKRcjX/zeUQ3gJxVicwLNgnc3LlzRZGhU+AxUOfPnxe7d++OjN
; 11anZJ4OEtUcQQXuK2c9CFzwTAvEA0PZ6080u6NsHmg7GxMZm3ZQEtarwxPp9aK57TVhzJEzZYk8D5
; gs62IyUMHgOstjtLy+2ygMdkUU9TCbcVZYHPBsC8TeccdCBTptrroq5zVtDCc0CWW+pRj2kI6VqNTI
; NtAnB5Qqeb15Fb4XWQjrMUym3AY/k+j50NT6Q0+HQBbBSIJseWdp5R14YuEYQN3p8FNNNCNp9NBESp
; wUb2zwO2ScA1GrogeAweXeR4G5vulKzgcdckX1SF8qjJpQOfKYCNNJ1zibsOKiw/fvy4VkuWCWi6wg
; g5Pv2YnAvvyRJC+oAtErhGQ6cGB+9mWih3AV4YPrwCMjZ5QtJk04WvCCCaHmfaeat2OiZ8GmQ+QAt7
; NBXKEmYWCTZj4HxDRzjAEnykep3SQRx0rsFjktIydubMmQmhUtpEtIEwC5guvkvnnIJQcV0IIXmvb9
; B0hREMoYjtGFCfeV/esBkB59vThcHjAhHC9ff3y5+mNTvf4GFMaJ7gyqOTw3dyXfhcQpgXXHFSvup+
; 4ZokQZY3aMG5w+exagQNgM9IA82nZ9MCzhV0Sd6OuF8VRKPi7TjoXIBnAx8hJuGummhxZjKZfUCZ9f
; uTzo1mY6IQvIgLyFyAlpSvqZyc1jB+pwuaa9gkcHPmzBGNgo5tD1QdxUX5wAd4UfAxoRF01I5hSZPT
; NYiuzeTYMcJHtj4wgcwVaFnkfs6V4x4ZGZkEXV6wwZoEzgd0SSEmJ0xCy2Tl4pqomL7B04WPyceNgn
; MIPxLJdBL7htH2eILnhDdTLXBZIfMJWlquxs1SFcpNQ8issE0ALgt0Jt6OUAypnYuoI6gUFTxlDCB9
; fTzph3BTR/ksoiUdN61ZnGMaYEUELSpf47UU5tmblO/2IY5EwTYJON/QsS0aE5NJqiuo2ISZNuClwZ
; cEIJOSljB2DEuavI2G0fS4sHPnzo2309kAlgSZKWgmdbU0YYT38cTdt99+e/x3vmGLBM4HdJwQblx5
; NRsl08bbJYHnAz4mqAqVg97AZqI3woLnQuiIV8sTMlPQTKT+uPCR33Mz4rOioHMJWyxwOuDpQMdJkK
; Sy2ac6GRMV01WYmcXr6cAXBhAZmrV6UcuHdJTQPMEKGzeLmzdvyhKNCWBpkNl4Mxfho64wQg2YTWeJ
; vrLClsRUInBZvB0nQ1sWvXVcuCzlg7zA04FP1/uxbITWMJ2cpygGjOycheTvAjBbb5YnaEGjZsdyIr
; 7fpVcL2r8AGXdjwjO3B0sAAAAASUVORK5CYII=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R22
M201 X2500 Y2500 Z400 E5000 ; sets maximum accelerations, mm/sec^2
M203 X180 Y180 Z12 E80 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T2500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MINI" ; printer model check
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S60 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S60 ; wait for bed temp
M204 T1250 ; set travel acceleration
G28 ; home all without mesh bed level
G29 ; mesh bed leveling 
M204 T2500 ; restore travel acceleration
M104 S215 ; set extruder temp
G92 E0
G1 Y-2 X179 F2400
G1 Z3 F720
M109 S215 ; wait for extruder temp

; intro line
G1 X170 F1000
G1 Z0.2 F720
G1 X110 E8 F900
G1 X40 E10 F700
G92 E0

M221 S95 ; set flow
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.2 ; Filament gcode LA 1.5
; ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-3.2 F4200
M73 P1 R22
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2
G1 Z.4
G1 X63.706 Y63.43 F9000
G1 Z.2 F720
G1 E3.2 F2400
M204 P800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X66.513 Y60.919 E.11809
G1 X69.559 Y58.704 E.11809
G1 X72.741 Y56.842 E.11559
G1 X76.165 Y55.274 E.11809
G1 X79.73 Y54.059 E.11809
G1 X83.399 Y53.208 E.11809
G1 X87.135 Y52.731 E.11809
G1 X90.773 Y52.631 E.11414
G1 X93.486 Y52.784 E.08519
G1 X97.214 Y53.324 E.11809
G1 X100.868 Y54.236 E.11809
G1 X104.411 Y55.512 E.11809
G1 X107.809 Y57.137 E.11809
G1 X111.025 Y59.096 E.11809
G1 X113.967 Y61.318 E.11558
G1 X116.732 Y63.875 E.11809
G1 X119.225 Y66.698 E.11809
G1 X120.769 Y68.779 E.08125
G1 X122.748 Y71.983 E.11809
G1 X124.395 Y75.371 E.11809
G1 X125.693 Y78.906 E.11808
G1 X126.628 Y82.554 E.11809
G1 X127.191 Y86.278 E.11808
G1 X127.377 Y90.04 E.11809
G1 X127.183 Y93.801 E.11809
G1 X126.612 Y97.524 E.11809
G1 X125.669 Y101.17 E.11809
G1 X124.364 Y104.703 E.11809
G1 X122.71 Y108.087 E.11809
G1 X120.724 Y111.287 E.11809
G1 X118.477 Y114.21 E.11559
G1 X115.897 Y116.953 E.11808
G1 X113.053 Y119.422 E.11809
G1 X109.975 Y121.593 E.11809
G1 X106.695 Y123.443 E.11808
G1 X103.362 Y124.907 E.11414
G1 X100.791 Y125.787 E.08519
G1 X97.135 Y126.691 E.11809
G1 X93.407 Y127.223 E.11809
G1 X89.644 Y127.378 E.11809
G1 X85.964 Y127.161 E.11559
G1 X82.245 Y126.566 E.11809
G1 X78.604 Y125.601 E.11809
G1 X75.08 Y124.273 E.11809
G1 X71.706 Y122.598 E.11809
G1 X69.492 Y121.253 E.08125
G1 X66.451 Y119.031 E.11809
G1 X63.649 Y116.514 E.11809
G1 X61.115 Y113.728 E.11809
G1 X58.874 Y110.701 E.11809
G1 X56.986 Y107.534 E.11559
G1 X55.389 Y104.124 E.11809
G1 X54.144 Y100.569 E.11809
G1 X53.262 Y96.908 E.11809
G1 X52.753 Y93.176 E.11809
G1 X52.623 Y89.412 E.11809
G1 X52.872 Y85.654 E.11809
G1 X53.498 Y81.94 E.11809
G1 X54.494 Y78.308 E.11809
G1 X55.851 Y74.795 E.11809
G1 X57.554 Y71.436 E.11809
G1 X59.515 Y68.369 E.11414
M73 P2 R22
G1 X61.166 Y66.211 E.08519
G1 X63.666 Y63.474 E.11621
M204 P1000
; printing object helper_disk.stl id:0 copy 0
G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X64.89 Y62.375 E-.912
;WIPE_END
G1 E-.048 F4200
G1 Z.4 F720
G1 X92.011 Y55.844 F9000
G1 Z.2 F720
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.419999
G1 F1200
G1 X93.155 Y55.931 E.03595
G1 X94.297 Y56.056 E.03604
G1 X95.435 Y56.22 E.03605
G1 X96.567 Y56.421 E.03604
G1 X97.691 Y56.661 E.03604
G1 X98.807 Y56.938 E.03604
G1 X99.913 Y57.253 E.03605
G1 X101.007 Y57.604 E.03604
G1 X102.089 Y57.992 E.03604
G1 X103.158 Y58.417 E.03605
G1 X104.211 Y58.877 E.03604
G1 X105.249 Y59.372 E.03605
G1 X106.269 Y59.901 E.03604
G1 X107.271 Y60.465 E.03604
G1 X108.253 Y61.062 E.03605
G1 X109.215 Y61.691 E.03604
G1 X110.155 Y62.353 E.03604
G1 X111.073 Y63.046 E.03604
G1 X111.966 Y63.769 E.03604
G1 X112.835 Y64.522 E.03604
G1 X113.678 Y65.303 E.03605
G1 X114.494 Y66.113 E.03604
G1 X115.283 Y66.949 E.03605
G1 X116.043 Y67.812 E.03604
G1 X116.774 Y68.699 E.03605
G1 X117.474 Y69.611 E.03604
G1 X118.144 Y70.545 E.03605
G1 X118.781 Y71.502 E.03604
G1 X119.386 Y72.479 E.03604
G1 X119.958 Y73.476 E.03604
G1 X120.497 Y74.492 E.03604
G1 X120.947 Y75.416 E.03223
G1 X121.469 Y76.576 E.03989
G1 X121.902 Y77.64 E.03602
G1 X122.3 Y78.719 E.03604
G1 X122.66 Y79.81 E.03604
G1 X122.984 Y80.913 E.03605
G1 X123.271 Y82.027 E.03604
G1 X123.52 Y83.149 E.03604
G1 X123.731 Y84.279 E.03605
G1 X123.904 Y85.415 E.03604
G1 X124.039 Y86.557 E.03605
G1 X124.136 Y87.702 E.03604
G1 X124.194 Y88.851 E.03604
G1 X124.213 Y90 E.03604
G1 X124.194 Y91.149 E.03604
G1 X124.136 Y92.298 E.03604
G1 X124.039 Y93.443 E.03604
G1 X123.904 Y94.585 E.03605
G1 X123.731 Y95.721 E.03604
G1 X123.52 Y96.851 E.03605
G1 X123.271 Y97.973 E.03604
G1 X122.984 Y99.087 E.03604
G1 X122.66 Y100.19 E.03605
G1 X122.3 Y101.281 E.03604
G1 X121.902 Y102.36 E.03604
G1 X121.469 Y103.425 E.03604
G1 X121 Y104.474 E.03604
G1 X120.497 Y105.508 E.03604
G1 X119.958 Y106.524 E.03604
G1 X119.386 Y107.521 E.03604
G1 X118.781 Y108.498 E.03604
G1 X118.144 Y109.455 E.03604
G1 X117.474 Y110.389 E.03605
G1 X116.774 Y111.301 E.03604
G1 X116.043 Y112.188 E.03605
G1 X115.283 Y113.051 E.03604
G1 X114.494 Y113.887 E.03605
G1 X113.678 Y114.697 E.03604
G1 X112.835 Y115.478 E.03605
G1 X111.966 Y116.231 E.03604
G1 X111.073 Y116.954 E.03604
G1 X110.155 Y117.647 E.03605
G1 X109.215 Y118.309 E.03604
G1 X108.253 Y118.938 E.03604
G1 X107.271 Y119.535 E.03605
G1 X106.269 Y120.099 E.03604
G1 X105.249 Y120.628 E.03604
G1 X104.211 Y121.123 E.03605
G1 X103.158 Y121.583 E.03604
G1 X102.202 Y121.963 E.03223
G1 X101.006 Y122.396 E.03989
G1 X99.913 Y122.747 E.03601
G1 X98.807 Y123.062 E.03605
G1 X97.691 Y123.339 E.03604
G1 X96.567 Y123.579 E.03604
G1 X95.435 Y123.78 E.03604
G1 X94.297 Y123.944 E.03605
G1 X93.155 Y124.069 E.03604
G1 X92.008 Y124.156 E.03604
G1 X90.981 Y124.199 E.03223
G1 X89.709 Y124.214 E.03989
G1 X88.561 Y124.185 E.03602
G1 X87.413 Y124.118 E.03604
G1 X86.269 Y124.011 E.03605
G1 X85.128 Y123.867 E.03604
G1 X83.993 Y123.684 E.03604
G1 X82.865 Y123.464 E.03604
G1 X81.745 Y123.205 E.03604
G1 X80.634 Y122.909 E.03604
G1 X79.534 Y122.576 E.03605
G1 X78.445 Y122.206 E.03604
G1 X77.37 Y121.8 E.03604
G1 X76.309 Y121.358 E.03604
G1 X75.263 Y120.88 E.03604
G1 X74.343 Y120.422 E.03223
G1 X73.222 Y119.821 E.03989
G1 X72.231 Y119.241 E.03601
G1 X71.258 Y118.627 E.03605
G1 X70.307 Y117.982 E.03604
G1 X69.378 Y117.304 E.03604
G1 X68.473 Y116.596 E.03605
G1 X67.591 Y115.858 E.03604
G1 X66.735 Y115.091 E.03604
G1 X65.906 Y114.295 E.03604
G1 X65.103 Y113.472 E.03604
G1 X64.328 Y112.623 E.03605
G1 X63.583 Y111.748 E.03604
G1 X62.867 Y110.848 E.03604
G1 X62.182 Y109.925 E.03604
G1 X61.529 Y108.979 E.03604
G1 X60.907 Y108.012 E.03605
G1 X60.318 Y107.025 E.03604
G1 X59.763 Y106.018 E.03604
G1 X59.242 Y104.993 E.03605
G1 X58.756 Y103.952 E.03604
G1 X58.305 Y102.894 E.03605
G1 X57.89 Y101.822 E.03604
G1 X57.511 Y100.737 E.03604
G1 X57.168 Y99.64 E.03604
G1 X56.863 Y98.531 E.03604
G1 X56.623 Y97.532 E.03223
G1 X56.365 Y96.286 E.03989
G1 X56.173 Y95.154 E.03602
G1 X56.019 Y94.014 E.03604
G1 X55.903 Y92.871 E.03604
G1 X55.826 Y91.724 E.03605
G1 X55.787 Y90.575 E.03604
G1 X55.787 Y89.425 E.03604
G1 X55.826 Y88.276 E.03604
G1 X55.903 Y87.129 E.03605
G1 X56.019 Y85.986 E.03604
G1 X56.173 Y84.846 E.03604
G1 X56.365 Y83.713 E.03605
G1 X56.595 Y82.587 E.03604
G1 X56.863 Y81.469 E.03604
G1 X57.168 Y80.36 E.03604
G1 X57.511 Y79.263 E.03605
G1 X57.89 Y78.178 E.03604
G1 X58.305 Y77.106 E.03604
G1 X58.756 Y76.048 E.03605
G1 X59.242 Y75.007 E.03604
G1 X59.763 Y73.982 E.03605
G1 X60.318 Y72.975 E.03604
G1 X60.907 Y71.988 E.03604
G1 X61.529 Y71.021 E.03605
G1 X62.113 Y70.175 E.03223
G1 X62.868 Y69.151 E.03989
G1 X63.583 Y68.252 E.03601
G1 X64.328 Y67.377 E.03604
G1 X65.103 Y66.528 E.03604
G1 X65.906 Y65.705 E.03604
G1 X66.735 Y64.909 E.03604
G1 X67.591 Y64.142 E.03604
G1 X68.473 Y63.404 E.03604
G1 X69.378 Y62.696 E.03605
G1 X70.307 Y62.018 E.03605
G1 X71.258 Y61.373 E.03604
G1 X72.231 Y60.759 E.03605
G1 X73.223 Y60.179 E.03604
G1 X74.234 Y59.632 E.03604
G1 X75.263 Y59.12 E.03605
G1 X76.309 Y58.642 E.03604
G1 X77.37 Y58.2 E.03604
G1 X78.445 Y57.794 E.03604
G1 X79.534 Y57.424 E.03604
G1 X80.634 Y57.091 E.03605
G1 X81.745 Y56.795 E.03604
G1 X82.865 Y56.536 E.03604
G1 X83.993 Y56.316 E.03604
G1 X85.128 Y56.133 E.03604
G1 X86.269 Y55.989 E.03604
G1 X87.413 Y55.882 E.03605
G1 X88.561 Y55.815 E.03604
G1 X89.71 Y55.786 E.03604
G1 X91.951 Y55.842 E.07029
M204 P1000
G1 X92.031 Y55.467 F9000
M204 P800
;TYPE:External perimeter
G1 F1200
G1 X93.189 Y55.555 E.03641
G1 X94.345 Y55.682 E.03644
G1 X95.495 Y55.847 E.03644
G1 X96.639 Y56.051 E.03644
G1 X97.776 Y56.293 E.03644
G1 X98.904 Y56.574 E.03644
G1 X100.022 Y56.892 E.03644
G1 X101.128 Y57.247 E.03644
G1 X102.222 Y57.64 E.03644
G1 X103.303 Y58.069 E.03644
G1 X104.368 Y58.534 E.03644
G1 X105.417 Y59.034 E.03644
G1 X106.448 Y59.57 E.03644
G1 X107.461 Y60.139 E.03644
G1 X108.455 Y60.743 E.03644
G1 X109.427 Y61.379 E.03644
G1 X110.377 Y62.048 E.03644
G1 X111.305 Y62.749 E.03644
G1 X112.208 Y63.48 E.03644
G1 X113.087 Y64.241 E.03644
G1 X113.939 Y65.031 E.03644
G1 X114.764 Y65.85 E.03644
G1 X115.562 Y66.695 E.03644
G1 X116.33 Y67.567 E.03644
G1 X117.069 Y68.464 E.03644
G1 X117.777 Y69.386 E.03644
G1 X118.454 Y70.331 E.03644
G1 X119.099 Y71.298 E.03644
G1 X119.71 Y72.286 E.03644
G1 X120.289 Y73.294 E.03644
G1 X120.833 Y74.321 E.03644
G1 X121.289 Y75.256 E.03261
G1 X121.816 Y76.428 E.04028
M73 P3 R22
G1 X122.254 Y77.504 E.03643
G1 X122.656 Y78.594 E.03644
G1 X123.02 Y79.698 E.03644
G1 X123.348 Y80.813 E.03645
G1 X123.638 Y81.939 E.03644
G1 X123.889 Y83.073 E.03644
G1 X124.103 Y84.216 E.03644
G1 X124.278 Y85.365 E.03644
G1 X124.414 Y86.519 E.03644
G1 X124.512 Y87.677 E.03644
G1 X124.57 Y88.838 E.03644
G1 X124.59 Y90 E.03644
G1 X124.57 Y91.162 E.03644
G1 X124.512 Y92.323 E.03644
G1 X124.414 Y93.481 E.03644
G1 X124.278 Y94.635 E.03644
G1 X124.103 Y95.784 E.03644
G1 X123.889 Y96.927 E.03644
G1 X123.638 Y98.061 E.03644
G1 X123.348 Y99.187 E.03644
G1 X123.02 Y100.302 E.03645
G1 X122.656 Y101.406 E.03644
G1 X122.254 Y102.496 E.03644
G1 X121.816 Y103.573 E.03644
G1 X121.342 Y104.634 E.03644
G1 X120.833 Y105.679 E.03644
G1 X120.289 Y106.706 E.03644
G1 X119.71 Y107.714 E.03644
G1 X119.099 Y108.702 E.03644
G1 X118.454 Y109.669 E.03644
G1 X117.777 Y110.614 E.03644
G1 X117.069 Y111.536 E.03644
G1 X116.33 Y112.433 E.03644
G1 X115.562 Y113.305 E.03644
G1 X114.764 Y114.15 E.03644
G1 X113.939 Y114.969 E.03644
G1 X113.087 Y115.759 E.03644
G1 X112.208 Y116.52 E.03644
G1 X111.305 Y117.251 E.03644
G1 X110.377 Y117.952 E.03644
G1 X109.427 Y118.621 E.03644
G1 X108.455 Y119.257 E.03644
G1 X107.461 Y119.861 E.03644
G1 X106.448 Y120.43 E.03644
G1 X105.417 Y120.966 E.03644
G1 X104.368 Y121.466 E.03645
G1 X103.303 Y121.931 E.03644
G1 X102.336 Y122.315 E.03261
G1 X101.128 Y122.753 E.04028
G1 X100.022 Y123.108 E.03643
G1 X98.904 Y123.426 E.03644
G1 X97.776 Y123.707 E.03644
G1 X96.639 Y123.949 E.03644
G1 X95.495 Y124.153 E.03644
G1 X94.345 Y124.318 E.03644
G1 X93.189 Y124.445 E.03644
G1 X92.03 Y124.533 E.03644
G1 X90.991 Y124.576 E.03261
G1 X89.707 Y124.591 E.04029
G1 X88.545 Y124.562 E.03643
G1 X87.385 Y124.494 E.03644
G1 X86.228 Y124.386 E.03644
G1 X85.075 Y124.24 E.03644
G1 X83.927 Y124.056 E.03644
G1 X82.786 Y123.832 E.03644
G1 X81.654 Y123.571 E.03644
G1 X80.531 Y123.272 E.03644
G1 X79.418 Y122.935 E.03644
G1 X78.318 Y122.561 E.03644
G1 X77.231 Y122.15 E.03644
G1 X76.158 Y121.703 E.03644
G1 X75.101 Y121.221 E.03644
G1 X74.17 Y120.757 E.03261
G1 X73.038 Y120.15 E.04029
G1 X72.035 Y119.563 E.03643
G1 X71.052 Y118.943 E.03644
G1 X70.09 Y118.29 E.03644
G1 X69.151 Y117.605 E.03644
G1 X68.235 Y116.889 E.03644
G1 X67.344 Y116.143 E.03644
G1 X66.479 Y115.367 E.03644
G1 X65.64 Y114.563 E.03644
G1 X64.829 Y113.731 E.03644
G1 X64.046 Y112.872 E.03644
G1 X63.292 Y111.987 E.03644
G1 X62.568 Y111.078 E.03644
G1 X61.876 Y110.144 E.03644
G1 X61.215 Y109.188 E.03644
G1 X60.586 Y108.211 E.03644
G1 X59.991 Y107.212 E.03644
G1 X59.43 Y106.195 E.03644
G1 X58.903 Y105.158 E.03644
G1 X58.412 Y104.105 E.03644
G1 X57.956 Y103.036 E.03644
G1 X57.536 Y101.953 E.03644
G1 X57.153 Y100.855 E.03644
G1 X56.806 Y99.746 E.03644
G1 X56.498 Y98.625 E.03644
G1 X56.255 Y97.614 E.03261
G1 X55.994 Y96.356 E.04029
G1 X55.8 Y95.21 E.03643
G1 X55.644 Y94.059 E.03644
G1 X55.527 Y92.902 E.03644
G1 X55.449 Y91.743 E.03644
G1 X55.41 Y90.581 E.03644
G1 X55.41 Y89.419 E.03644
G1 X55.449 Y88.257 E.03644
G1 X55.527 Y87.098 E.03644
G1 X55.644 Y85.941 E.03644
G1 X55.8 Y84.79 E.03644
G1 X55.994 Y83.644 E.03644
G1 X56.227 Y82.505 E.03644
G1 X56.498 Y81.375 E.03644
G1 X56.806 Y80.254 E.03644
G1 X57.153 Y79.145 E.03644
G1 X57.536 Y78.047 E.03644
G1 X57.956 Y76.964 E.03644
G1 X58.412 Y75.895 E.03644
G1 X58.903 Y74.842 E.03644
G1 X59.43 Y73.805 E.03644
G1 X59.991 Y72.788 E.03644
G1 X60.586 Y71.789 E.03644
G1 X61.215 Y70.812 E.03644
G1 X61.806 Y69.956 E.03261
G1 X62.569 Y68.922 E.04028
G1 X63.292 Y68.013 E.03643
G1 X64.046 Y67.128 E.03644
G1 X64.829 Y66.269 E.03644
G1 X65.64 Y65.437 E.03644
G1 X66.479 Y64.633 E.03644
G1 X67.344 Y63.857 E.03644
G1 X68.235 Y63.111 E.03644
G1 X69.151 Y62.395 E.03644
G1 X70.09 Y61.71 E.03644
G1 X71.052 Y61.057 E.03644
G1 X72.035 Y60.437 E.03644
G1 X73.038 Y59.85 E.03644
G1 X74.06 Y59.298 E.03644
G1 X75.101 Y58.779 E.03644
G1 X76.158 Y58.297 E.03644
G1 X77.231 Y57.85 E.03644
G1 X78.318 Y57.439 E.03644
G1 X79.418 Y57.065 E.03644
G1 X80.531 Y56.728 E.03644
G1 X81.654 Y56.429 E.03644
G1 X82.786 Y56.168 E.03644
G1 X83.927 Y55.944 E.03644
G1 X85.075 Y55.76 E.03644
G1 X86.228 Y55.614 E.03644
G1 X87.385 Y55.506 E.03644
G1 X88.545 Y55.438 E.03644
G1 X89.707 Y55.409 E.03644
G1 X91.971 Y55.466 E.07102
M204 P1000
G1 X92.213 Y55.824 F9000
G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X93.189 Y55.555 E-.67672
G1 X93.611 Y55.601 E-.23528
;WIPE_END
G1 E-.048 F4200
G1 Z.4 F720
G1 X111.59 Y63.61 F9000
G1 Z.2 F720
G1 E3.2 F2400
M204 P800
; stop printing object helper_disk.stl id:0 copy 0
; my code start

; my code end
G1 E-2.24 F4200
;WIPE_START
G1 F7200;_WIPE
G1 X64.695 Y67.12 E-.912
;WIPE_END
G1 E-.048 F4200
G1 Z1.15 F720
M107
;TYPE:Custom
; Filament-specific end gcode
G1 E-1 F2100 ; retract
G1 Z2.95 F720 ; Move print head up
G1 X178 Y178 F4200 ; park print head
G1 Z30.95 F720 ; Move print head further up
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 1542.61
; filament used [cm3] = 3.71
; filament used [g] = 4.60
; filament cost = 0.17
; total filament used [g] = 4.60
; total filament cost = 0.17
; estimated printing time (normal mode) = 22m 52s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MINI
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1 F2100 ; retract\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F720 ; Move print head up{endif}\nG1 X178 Y178 F4200 ; park print head\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM900 K0 ; reset LA\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 35
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 36.29
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.15
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_travel = 2500
; machine_max_acceleration_x = 2500
; machine_max_acceleration_y = 2500
; machine_max_acceleration_z = 400
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 180
; machine_max_feedrate_y = 180
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 10
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 180
; max_print_speed = 150
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 40
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.15mm QUALITY @MINI
; printer_model = MINI
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MINI\n
; printer_settings_id = Original Prusa MINI & MINI+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 3.2
; retract_length_toolchange = 4
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 179
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM204 T1250 ; set travel acceleration\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM204 T[machine_max_acceleration_travel] ; restore travel acceleration\nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0\nG1 Y-2 X179 F2400\nG1 Z3 F720\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X170 F1000\nG1 Z0.2 F720\nG1 X110 E8 F900\nG1 X40 E10 F700\nG92 E0\n\nM221 S95 ; set flow
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 4
; thumbnails = 16x16,220x124
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 8
; top_solid_min_thickness = 0.7
; travel_speed = 150
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
