; generated by PrusaSlicer 2.5.0+win64 on 2023-05-24 at 22:21:43 UTC


;
; thumbnail begin 16x16 312
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAr0lEQVR4AeWSvQrCMBSF+1DV/EJRKj
; oYFKGDiEJBCi5uFVxcfQQfwMVJFxdx8smO3kyFxFhxs8MHIXC+3Jwk0lrjF6I/FJiuwm4icMo5HiuG
; W8HsmvayVIUF876yoXeQbG2kX5AmOhiuSuggR0Aj1hEQ+0y4gs1Y1hZsR9wVDBJpx/sUvhctW7S3xG
; lP4rpsB8PV+3ufkcosDcNxwXDJY5xfHGYC5TBGR/FGfOVveQLYyeD0fUqbVwAAAABJRU5ErkJggg==
; thumbnail end
;

;
; thumbnail begin 220x124 2760
; iVBORw0KGgoAAAANSUhEUgAAANwAAAB8CAYAAAACRt5vAAAH3UlEQVR4Ae3c6XNTVRjHcf4REFqSLm
; naBrqQm5ukG91baG2hdEnpQqF1ZJhhpiwiDOBQZoBhFBAVEBfcRmBQxJFRX/iXPd4nsVqhS5Imh/s8
; 5/fi88pxrO3zzTn33Ju7xXVdAgAztkj6YQGkQ3AABiE4AIMQHIBBCA7AIAQHYBCCAzAIwQEYhOAADE
; JwAAYhOACDEByAQQgOwCAEB2AQggMwCMEBGITgAAxCcAAGITif6GuJ0Vy3Q8f7HDo/GKWbI1H6IrUn
; 7dlMxsu5xlXxP/t+KuPuWObfXRqO0uJ+hyY6YjTcFqO2pKzfh1YIzjAefA6Lo1qO6a/5RiP4v8VBco
; zLIUr63WmA4IqMA+OVhgedVyNTcWWLfyb+2fgDAAEWH4IrguUVzOTqVSi8LeUVENvQ4kBwBcJbNB5U
; P65im1n9+HoQK1/hILhN4u2ixJUsV/z/yKs2H+5I+vv4DYLLA3/i8ye/pGAKuerxYQ9WvfwguBzYHN
; pqEF7uEFwWEBrCKxQEtw4+pUNouYWHa7z1Ibg18GGIpGH3C77G498dbimsDsG9grdGfC9K0pD7EbaZ
; q0NwK2BVKyysdq9DcG7mWo0fb5I0zJLg2s5FcMt422PDjes3jX/H/MibpNkoBquD48exJA2tdLzF5K
; 8fSZoRBFcg/IeXNKya8HWdpFlBcJvEzwRKGlCN+G8gaWYQXJ5wEukf/O0KSbOD4HLEF+2SBtIGtm0v
; rQkOByT+ZdPppRXB8T0gSQNoGz695A9ESTOF4NaBR7X8j+/T2fBEivrg8ASJHDYcoqgODtdt8mi/nl
; MbHG9P8MiWPNq3lmqDw81tuTRvLVUGx5+QkgYM/o9PLbV+l05lcHgtgnz8N5Q0c9YGh9VNB17lNH6H
; Tl1wuHbTQ+MDzuqCw8mkHhpPLFUFh/tu+mi7L6cqOD5OljRMsDFttwhUBYftpD78HKykGbQmOJxO6q
; XptFJNcPhyqV6aruPUBIfbAXppuo5TExwOTPTir1hJmkUrguO3+0oaIsiepoMTNcHhW9168emzpFm0
; IjjcEtCLn6uUNIsIDhAcgkNwgODEejzVIGqIIHvPZxpEzaIVwT0crxc1RJC9J4frRM2iFcHdOiRriC
; B7D0brRc2iFcFdGsAKp9WVQaxwvjPfhWs4rd7twgrnO8PNCE6r0aZdombRiuCa4g49O7xL1CDBxn6f
; q6fmGJ408aW7B2pFDRNs7MOBKlEzaFVwCx11ooYJNjbdhOB8qyvRiG2lIryd7IrtFjWDVgXHbg3ViB
; oqWNv1/pCo2bMyuOnWCP15FCeW0vHqti9WI2r2rAyOTyvvH8QqJ93tgUpqdnW9sUtlcAyrnGy8us0o
; OyxRHRyvcp8MV4saMvjPUk+FytVNbXAs1VxLP+HEUpxfZ+po0AmLmjUE52ZWuQs9VdhaCrPYEhA1Zw
; huhYFkHd0frhI1cDa72V9B3cruu1kVHJtuqaYnqYiowbPRjxMRGnPKRM0WglsFby1PtofoxfRuUQNo
; Ez6VnHdLRc0VgltHWzxKV3srcD3n09hOeddtbTE97y2xPjjGz1kuITrfubB3J3XE9HyjG8GtcKgpQr
; cHw4jOJz7oDFJfLCJqhhBcPtHtr0R0Poit17LYrAxuObprfYjuTTnvbSM1PpiM4DaI7kpPBb2cxdu+
; TOEDkjMtpVaubNYHx3oTDXS+o4we4z5d0fEXg4+72606IEFwq+j0Ti/PtpfT14dqsMUsks+Gqmg6Wm
; LN0b+L4NbX5Dp0pDlMN/oq6DdsMQuGt5CXO4I0EdX9fGQuENwKQ8nddK496K12+GrPZj08GKaje7bS
; PsfOw5G1ILhXdMYb6VhziK73ltMveBwsZ3ytdrkjQJPRUlXvkywUBLcGXu3e2xukBwfC9Aeu7bJyy7
; u/Oeetar1Orai/tUkIbh18bTfZVE1n24L05Ug1wlvDp29XpUMbcvS9ZavQEFwWOrxtZipZTWfaApnw
; 5hDecmgn4ttpJFqG7WOWEFwOeuL1NJEM0+nWAN0brqLnU/Zd472YqaOPvK3jbONWhJYHBJeH1ng0Hd
; 4pL7yr3WX0w3it+lXvkXefcsn7f+XQBqMhhJYnBLcJfI03EN9FC8kgnW0toY8HQ+lVT0t8HBmf1s5H
; t9F4Ywn1OdWi/j5+hOAKpNvbbo4kqv+N70ZfOT0arREXH0fGPztHNtWwzVvNKqkVT4gUDIIrgpXxLb
; bs9LadQbo3VEVPJyO+C/Ab70OBv650rrWUjnjbxdE9gXRk7Y7dzzwWC4IrMt529sfraDwRpnkvwBPJ
; Urrk3RjmrRo/Y/g0FaGfDWxD+X2P33px3RmoTH8X7WRyBx3zVrHp6A46GK2gHu/eWdL7WSX9biVCcI
; bxUPMKOBSvpclEiOYTmQhPt5TQ+2076aIX4zUvxjsDIfrcu+nO+FEzfvPYqx7/47ux2rSvvFsWd73r
; SMZBX2wP0GJTCb3jvEULzjaadUrSb8biF63a/tT+m4LgfKLVjaZD3O8dwnCMo/EwpeIhmo2X0dFEIG
; 0hUUoL8VKaX+GY620F3QBNuUFKueWUipXTWKyShmJh6ncj1OnWU4vS14ZLhOAADEJwAAYhOACDEByA
; QQgOwCAEB2AQggMwCMEBGITgAAxCcAAGITgAgxAcgEEIDsAgBAdgEIIDMAjBARiE4AAMQnAABiE4AI
; P+BgJAOUQbJVkOAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M201 X2500 Y2500 Z400 E5000 ; sets maximum accelerations, mm/sec^2
M203 X180 Y180 Z12 E80 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T2500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MINI" ; printer model check
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S60 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S60 ; wait for bed temp
M204 T1250 ; set travel acceleration
G28 ; home all without mesh bed level
G29 ; mesh bed leveling 
M204 T2500 ; restore travel acceleration
M104 S215 ; set extruder temp
G92 E0
G1 Y-2 X179 F2400
G1 Z3 F720
M109 S215 ; wait for extruder temp

; intro line
M73 P8 R0
G1 X170 F1000
G1 Z0.2 F720
M73 P9 R0
G1 X110 E8 F900
G1 X40 E10 F700
G92 E0

M221 S95 ; set flow
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.2 ; Filament gcode LA 1.5
; ; Filament gcode LA 1.0
M107
;Z:0.2
;HEIGHT:0.2
G92 E0.0
;0.2


M73 P17 R0
G1 E-3.2 F4200
M73 P28 R0
G1 Z.2 F720
;0.2
G1 Z.4
G1 X19.56 Y148.394 F9000
G1 Z.2 F720
M73 P30 R0
G1 E3.2 F2400
M204 P800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X20.622 Y148.254 E.03359
G1 X21.693 Y148.222 E.03358
G1 X22.761 Y148.297 E.03358
G1 X23.817 Y148.48 E.03359
G1 X24.848 Y148.768 E.03358
G1 X25.846 Y149.158 E.03358
G1 X27.492 Y150.084 E.05922
G1 X28.343 Y150.734 E.03359
M73 P31 R0
G1 X29.125 Y151.466 E.03358
G1 X29.83 Y152.273 E.03359
G1 X30.449 Y153.147 E.03358
G1 X31.371 Y154.961 E.06381
G1 X31.712 Y155.976 E.03358
G1 X31.95 Y157.021 E.03359
G1 X32.081 Y158.084 E.03358
G1 X32.104 Y159.155 E.03359
M73 P32 R0
G1 X32.019 Y160.223 E.03358
G1 X31.828 Y161.277 E.03359
G1 X31.235 Y163.07 E.05922
G1 X30.761 Y164.03 E.03358
G1 X30.193 Y164.938 E.03359
G1 X28.873 Y166.487 E.0638
G1 X28.067 Y167.193 E.03359
G1 X27.194 Y167.814 E.03359
G1 X26.263 Y168.343 E.03358
M73 P33 R0
G1 X25.283 Y168.777 E.03358
G1 X24.265 Y169.109 E.03358
G1 X23.219 Y169.338 E.03358
G1 X21.335 Y169.48 E.05922
G1 X20.266 Y169.412 E.03359
G1 X19.21 Y169.237 E.03358
G1 X17.272 Y168.614 E.0638
G1 X15.611 Y167.716 E.05922
G1 X14.749 Y167.081 E.03358
M73 P34 R0
G1 X13.955 Y166.362 E.03358
G1 X13.237 Y165.567 E.03358
G1 X12.603 Y164.704 E.03358
G1 X11.65 Y162.905 E.0638
G1 X11.292 Y161.896 E.03359
G1 X11.037 Y160.855 E.03358
G1 X10.888 Y159.795 E.03359
G1 X10.847 Y158.724 E.03358
M73 P35 R0
G1 X10.914 Y157.655 E.03358
G1 X11.088 Y156.598 E.03359
G1 X11.367 Y155.564 E.03359
G1 X11.749 Y154.564 E.03358
G1 X12.661 Y152.91 E.05922
G1 X13.304 Y152.053 E.03358
G1 X14.029 Y151.265 E.03359
G1 X14.83 Y150.554 E.03359
G1 X15.699 Y149.927 E.03358
G1 X17.505 Y148.989 E.0638
M73 P36 R0
G1 X18.518 Y148.64 E.03358
G1 X19.502 Y148.408 E.0317
M204 P1000
G1 X19.588 Y148.774 F9000
M204 P800
G1 F1200
G1 X20.657 Y148.629 E.03382
G1 X21.689 Y148.599 E.03239
G1 X22.72 Y148.672 E.03239
G1 X23.738 Y148.849 E.0324
G1 X24.733 Y149.127 E.03239
G1 X25.695 Y149.504 E.03239
G1 X27.275 Y150.393 E.05684
M73 P37 R0
G1 X28.097 Y151.019 E.03239
G1 X28.851 Y151.725 E.03239
G1 X29.531 Y152.503 E.0324
G1 X30.128 Y153.346 E.03239
G1 X31.022 Y155.103 E.06182
G1 X31.351 Y156.083 E.03239
G1 X31.579 Y157.09 E.0324
G1 X31.705 Y158.116 E.03239
G1 X31.727 Y159.149 E.03239
M73 P38 R0
G1 X31.645 Y160.178 E.03239
G1 X31.46 Y161.195 E.0324
G1 X30.891 Y162.916 E.05684
G1 X30.434 Y163.843 E.03239
G1 X29.886 Y164.719 E.03239
G1 X28.607 Y166.22 E.06182
G1 X27.83 Y166.9 E.0324
G1 X26.987 Y167.498 E.0324
G1 X26.089 Y168.009 E.03239
M73 P39 R0
G1 X25.144 Y168.426 E.03239
G1 X24.162 Y168.747 E.03239
G1 X23.153 Y168.967 E.03239
G1 X21.345 Y169.103 E.05684
G1 X20.314 Y169.038 E.0324
G1 X19.295 Y168.869 E.03239
G1 X17.418 Y168.266 E.06182
G1 X15.823 Y167.404 E.05684
G1 X14.991 Y166.792 E.03239
M73 P40 R0
G1 X14.225 Y166.099 E.03239
G1 X13.532 Y165.332 E.03239
G1 X12.92 Y164.5 E.03239
G1 X11.997 Y162.757 E.06182
G1 X11.652 Y161.784 E.0324
G1 X11.407 Y160.78 E.03239
G1 X11.264 Y159.757 E.03239
G1 X11.224 Y158.724 E.03239
G1 X11.289 Y157.693 E.03239
M73 P41 R0
G1 X11.457 Y156.674 E.03239
G1 X11.727 Y155.677 E.03239
G1 X12.096 Y154.712 E.03239
G1 X12.971 Y153.124 E.05684
G1 X13.591 Y152.297 E.03239
G1 X14.29 Y151.537 E.03239
G1 X15.063 Y150.851 E.0324
G1 X15.9 Y150.246 E.03239
G1 X17.65 Y149.338 E.06182
G1 X18.627 Y149.001 E.03239
M73 P42 R0
G1 X19.53 Y148.788 E.02908
M204 P1000
G1 X19.616 Y149.155 F9000
M204 P800
G1 F1200
G1 X20.692 Y149.005 E.03406
G1 X21.686 Y148.976 E.0312
G1 X22.679 Y149.047 E.0312
G1 X23.659 Y149.218 E.0312
G1 X24.618 Y149.486 E.0312
G1 X25.544 Y149.85 E.0312
G1 X27.058 Y150.701 E.05446
G1 X27.85 Y151.304 E.0312
M73 P43 R0
G1 X28.577 Y151.984 E.0312
G1 X29.765 Y153.477 E.05984
G1 X30.263 Y154.338 E.0312
G1 X30.673 Y155.245 E.0312
G1 X30.989 Y156.189 E.0312
G1 X31.208 Y157.16 E.03121
G1 X31.329 Y158.147 E.0312
G1 X31.35 Y159.142 E.0312
G1 X31.27 Y160.134 E.0312
G1 X31.091 Y161.113 E.0312
M73 P44 R0
G1 X30.546 Y162.762 E.05446
G1 X30.107 Y163.655 E.0312
G1 X29.579 Y164.499 E.0312
G1 X28.342 Y165.952 E.05983
G1 X27.592 Y166.607 E.0312
G1 X26.781 Y167.183 E.0312
G1 X25.916 Y167.674 E.0312
G1 X25.005 Y168.076 E.0312
G1 X24.059 Y168.384 E.0312
G1 X23.086 Y168.595 E.0312
M73 P45 R0
G1 X21.354 Y168.726 E.05446
G1 X19.458 Y168.519 E.05983
G1 X18.495 Y168.266 E.0312
G1 X17.563 Y167.918 E.0312
G1 X16.67 Y167.478 E.0312
G1 X15.826 Y166.951 E.0312
G1 X14.407 Y165.745 E.05839
G1 X13.237 Y164.296 E.05839
M73 P46 R0
G1 X12.731 Y163.439 E.0312
G1 X12.314 Y162.535 E.0312
G1 X11.776 Y160.704 E.05983
G1 X11.639 Y159.719 E.0312
G1 X11.601 Y158.724 E.0312
G1 X11.664 Y157.731 E.0312
G1 X11.827 Y156.749 E.0312
G1 X12.087 Y155.789 E.0312
G1 X12.443 Y154.86 E.0312
G1 X13.282 Y153.339 E.05446
M73 P47 R0
G1 X13.878 Y152.542 E.0312
G1 X14.551 Y151.809 E.0312
G1 X15.295 Y151.148 E.0312
G1 X16.101 Y150.565 E.0312
G1 X17.795 Y149.686 E.05984
G1 X18.736 Y149.362 E.0312
G1 X19.557 Y149.169 E.02645
M204 P1000
; printing object helper_disk.stl id:0 copy 0
G1 E-2.24 F4200
;WIPE_START
G1 F7200
M73 P48 R0
G1 X20.692 Y149.005 E-.63505
G1 X21.191 Y148.99 E-.27695
;WIPE_END
G1 E-.048 F4200
G1 Z.4 F720
G1 X27.555 Y156.003 F9000
G1 Z.2 F720
G1 E3.2 F2400
M204 P800
;TYPE:Perimeter
;WIDTH:0.419999
G1 F1200
G1 X27.951 Y157.077 E.0359
G1 X28.033 Y157.449 E.01195
G1 X28.137 Y158.085 E.02019
G1 X28.18 Y158.717 E.01986
G1 X28.186 Y159.076 E.01126
G1 X28.129 Y159.75 E.02121
G1 X28.005 Y160.415 E.0212
M73 P49 R0
G1 X27.817 Y161.055 E.02091
G1 X27.35 Y162.1 E.0359
G1 X26.999 Y162.667 E.02091
G1 X26.587 Y163.203 E.0212
G1 X26.123 Y163.695 E.0212
G1 X25.612 Y164.138 E.02121
G1 X25.059 Y164.527 E.0212
G1 X24.469 Y164.859 E.0212
G1 X23.849 Y165.129 E.02121
G1 X23.206 Y165.336 E.0212
G1 X22.544 Y165.477 E.0212
G1 X21.872 Y165.551 E.02121
G1 X21.205 Y165.557 E.02091
G1 X20.069 Y165.413 E.0359
G1 X19.425 Y165.241 E.02091
M73 P50 R0
G1 X18.792 Y165.002 E.0212
G1 X18.187 Y164.701 E.02121
G1 X17.615 Y164.34 E.0212
G1 X17.082 Y163.923 E.02121
G1 X16.594 Y163.455 E.02121
G1 X16.155 Y162.94 E.0212
G1 X15.776 Y162.392 E.02091
G1 X15.257 Y161.371 E.0359
G1 X15.037 Y160.741 E.02091
G1 X14.88 Y160.084 E.0212
G1 X14.789 Y159.414 E.0212
G1 X14.766 Y158.738 E.0212
G1 X14.812 Y158.063 E.0212
G1 X14.925 Y157.396 E.02121
G1 X15.104 Y156.744 E.0212
G1 X15.349 Y156.113 E.02121
M73 P51 R0
G1 X15.655 Y155.511 E.0212
G1 X16.021 Y154.942 E.02121
G1 X16.442 Y154.412 E.02121
G1 X16.907 Y153.935 E.02091
G1 X17.809 Y153.23 E.0359
G1 X18.385 Y152.893 E.02091
G1 X19 Y152.612 E.0212
G1 X19.641 Y152.394 E.02121
G1 X20.299 Y152.242 E.0212
G1 X20.97 Y152.157 E.02121
G1 X21.646 Y152.14 E.0212
G1 X22.321 Y152.191 E.02121
G1 X22.987 Y152.31 E.0212
G1 X23.637 Y152.495 E.02121
G1 X24.266 Y152.745 E.02121
M73 P52 R0
G1 X24.866 Y153.056 E.0212
G1 X25.432 Y153.427 E.02121
G1 X25.957 Y153.852 E.0212
G1 X26.438 Y154.328 E.02121
G1 X26.868 Y154.851 E.0212
G1 X27.243 Y155.413 E.02121
G1 X27.527 Y155.95 E.01903
M204 P1000
G1 X27.9 Y155.849 F9000
M204 P800
;TYPE:External perimeter
G1 F1200
G1 X28.313 Y156.971 E.03749
G1 X28.401 Y157.368 E.01275
G1 X28.512 Y158.041 E.02138
G1 X28.557 Y158.71 E.02105
G1 X28.563 Y159.089 E.01186
G1 X28.503 Y159.8 E.0224
G1 X28.372 Y160.503 E.0224
G1 X28.171 Y161.185 E.0223
G1 X27.684 Y162.277 E.03749
M73 P53 R0
G1 X27.309 Y162.882 E.0223
G1 X26.874 Y163.448 E.0224
G1 X26.384 Y163.968 E.0224
G1 X25.844 Y164.436 E.0224
G1 X25.26 Y164.847 E.0224
G1 X24.638 Y165.197 E.0224
G1 X23.983 Y165.483 E.0224
G1 X23.303 Y165.701 E.0224
G1 X22.604 Y165.85 E.0224
G1 X21.894 Y165.928 E.0224
G1 X21.183 Y165.934 E.0223
G1 X19.996 Y165.784 E.03749
G1 X19.309 Y165.6 E.0223
G1 X18.641 Y165.348 E.0224
M73 P54 R0
G1 X18.001 Y165.03 E.0224
G1 X17.397 Y164.648 E.0224
G1 X16.835 Y164.208 E.0224
G1 X16.319 Y163.714 E.0224
G1 X15.856 Y163.17 E.0224
G1 X15.451 Y162.585 E.0223
G1 X14.909 Y161.519 E.03749
G1 X14.675 Y160.848 E.0223
G1 X14.508 Y160.153 E.0224
G1 X14.413 Y159.445 E.0224
G1 X14.389 Y158.731 E.0224
G1 X14.437 Y158.019 E.0224
G1 X14.556 Y157.314 E.0224
G1 X14.746 Y156.626 E.0224
G1 X15.004 Y155.96 E.0224
M73 P55 R0
G1 X15.328 Y155.323 E.0224
G1 X15.714 Y154.722 E.0224
G1 X16.159 Y154.163 E.0224
G1 X16.655 Y153.653 E.0223
G1 X17.597 Y152.917 E.03749
G1 X18.211 Y152.558 E.0223
G1 X18.861 Y152.261 E.0224
G1 X19.537 Y152.031 E.0224
G1 X20.233 Y151.871 E.0224
G1 X20.942 Y151.781 E.0224
G1 X21.656 Y151.763 E.0224
G1 X22.368 Y151.817 E.0224
G1 X23.072 Y151.942 E.0224
G1 X23.759 Y152.138 E.0224
G1 X24.423 Y152.401 E.0224
M73 P56 R0
G1 X25.057 Y152.73 E.0224
G1 X25.654 Y153.122 E.0224
G1 X26.209 Y153.571 E.0224
G1 X26.717 Y154.074 E.0224
G1 X27.171 Y154.626 E.0224
G1 X27.567 Y155.22 E.0224
G1 X27.872 Y155.795 E.02042
M204 P1000
G1 X27.663 Y156.171 F9000
G1 E-2.24 F4200
;WIPE_START
G1 F7200
G1 X28.313 Y156.971 E-.69564
G1 X28.398 Y157.352 E-.21636
;WIPE_END
G1 E-.048 F4200
G1 Z.4 F720
G1 X24.965 Y153.257 F9000
G1 Z.2 F720
M73 P57 R0
G1 E3.2 F2400
M204 P800
;TYPE:Solid infill
;WIDTH:0.420794
G1 F1200
G1 X26.231 Y154.523 E.05625
G1 X26.64 Y155.019 E.02022
G1 X26.999 Y155.558 E.02035
G1 X27.298 Y156.124 E.0201
G1 X24.207 Y153.033 E.13734
G1 X23.546 Y152.763 E.02245
M73 P58 R0
G1 X23.346 Y152.707 E.00652
G1 X27.61 Y156.97 E.18944
G1 X27.679 Y157.157 E.00627
G1 X27.797 Y157.692 E.01721
G1 X22.641 Y152.536 E.22911
G1 X22.285 Y152.472 E.01136
M73 P59 R0
G1 X22.024 Y152.453 E.00824
G1 X27.879 Y158.308 E.26017
G1 X27.899 Y158.863 E.01745
M73 P60 R0
G1 X21.465 Y152.428 E.28593
G1 X20.948 Y152.445 E.01625
M73 P61 R0
G1 X27.877 Y159.375 E.3079
G1 X27.822 Y159.854 E.01516
M73 P62 R0
G1 X20.473 Y152.505 E.32653
G1 X20.029 Y152.595 E.01425
M73 P63 R0
G1 X27.738 Y160.304 E.34255
G1 X27.62 Y160.721 E.01361
M73 P64 R0
G1 X19.604 Y152.705 E.35617
G1 X19.206 Y152.841 E.01324
M73 P65 R0
G1 X27.48 Y161.115 E.36767
G1 X27.315 Y161.485 E.01271
M73 P66 R0
G1 X18.831 Y153 E.377
G1 X18.468 Y153.172 E.01261
M73 P67 R0
G1 X27.15 Y161.854 E.38578
G1 X26.958 Y162.196 E.01233
M73 P68 R0
G1 X18.131 Y153.369 E.39222
G1 X17.969 Y153.464 E.00591
M73 P69 R0
G1 X17.813 Y153.586 E.00621
G1 X26.752 Y162.525 E.39719
G1 X26.519 Y162.827 E.01197
M73 P71 R0
G1 X17.513 Y153.82 E.4002
G1 X17.213 Y154.055 E.01196
M73 P72 R0
G1 X26.277 Y163.119 E.40277
G1 X26.018 Y163.394 E.01188
M73 P73 R0
G1 X16.935 Y154.311 E.40359
G1 X16.671 Y154.582 E.01187
M73 P74 R0
G1 X25.741 Y163.652 E.40302
G1 X25.455 Y163.9 E.0119
M73 P75 R0
G1 X16.433 Y154.878 E.40089
G1 X16.203 Y155.182 E.01199
M73 P77 R0
G1 X25.143 Y164.122 E.39727
G1 X24.822 Y164.336 E.01211
M73 P78 R0
G1 X15.993 Y155.507 E.3923
G1 X15.801 Y155.849 E.01232
M73 P79 R0
G1 X24.48 Y164.528 E.38568
G1 X24.12 Y164.703 E.01257
M73 P80 R0
G1 X15.62 Y156.203 E.37769
G1 X15.469 Y156.586 E.01294
M73 P81 R0
G1 X23.748 Y164.865 E.36789
G1 X23.344 Y164.995 E.01335
M73 P82 R0
G1 X15.332 Y156.983 E.35601
G1 X15.216 Y157.402 E.01365
M73 P83 R0
G1 X22.922 Y165.108 E.3424
M73 P84 R0
G1 X22.48 Y165.2 E.01419
M73 P85 R0
G1 X15.134 Y157.854 E.32642
G1 X15.077 Y158.331 E.01511
M73 P86 R0
G1 X21.998 Y165.253 E.30755
G1 X21.483 Y165.271 E.01621
G1 X15.053 Y158.841 E.28572
M73 P87 R0
G1 X15.072 Y159.395 E.0174
G1 X20.911 Y165.234 E.25947
G1 X20.299 Y165.157 E.01938
M73 P88 R0
G1 X15.155 Y160.013 E.22857
G1 X15.33 Y160.722 E.02294
M73 P89 R0
G1 X19.604 Y164.996 E.18993
G1 X18.905 Y164.742 E.02336
M73 P90 R0
G1 X18.728 Y164.654 E.00624
G1 X15.708 Y161.635 E.13416
G1 X16.019 Y162.246 E.02156
G1 X16.38 Y162.768 E.01991
G1 X16.798 Y163.259 E.02027
G1 X17.968 Y164.429 E.052
M204 P1000
; stop printing object helper_disk.stl id:0 copy 0
; my code start
; my code end
G1 E-2.24 F4200
;WIPE_START
G1 F7200;_WIPE
G1 X16.805 Y163.265 E-.912
;WIPE_END
G1 E-.048 F4200
M73 P91 R0
G1 Z.4 F720
M107
;TYPE:Custom
; Filament-specific end gcode
G1 E-1 F2100 ; retract
G1 Z2.2 F720 ; Move print head up
G1 X178 Y178 F4200 ; park print head
G1 Z30.2 F720 ; Move print head further up
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M900 K0 ; reset LA
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 20.21
; filament used [cm3] = 0.05
; filament used [g] = 0.06
; filament cost = 0.00
; total filament used [g] = 0.06
; total filament cost = 0.00
; estimated printing time (normal mode) = 55s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 5
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MINI
; deretract_speed = 40
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1 F2100 ; retract\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F720 ; Move print head up{endif}\nG1 X178 Y178 F4200 ; park print head\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM900 K0 ; reset LA\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 35
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 36.29
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusament PLA"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.15
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_travel = 2500
; machine_max_acceleration_x = 2500
; machine_max_acceleration_y = 2500
; machine_max_acceleration_z = 400
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 180
; machine_max_feedrate_y = 180
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 10
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 180
; max_print_speed = 150
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 40
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.15mm QUALITY @MINI
; printer_model = MINI
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MINI\n
; printer_settings_id = Original Prusa MINI & MINI+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 3.2
; retract_length_toolchange = 4
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 179
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM204 T1250 ; set travel acceleration\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM204 T[machine_max_acceleration_travel] ; restore travel acceleration\nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0\nG1 Y-2 X179 F2400\nG1 Z3 F720\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X170 F1000\nG1 Z0.2 F720\nG1 X110 E8 F900\nG1 X40 E10 F700\nG92 E0\n\nM221 S95 ; set flow
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 4
; thumbnails = 16x16,220x124
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 8
; top_solid_min_thickness = 0.7
; travel_speed = 150
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
